name: usta_kz
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  firebase_storage: ^12.4.10
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
